[package]
name = "nesir"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
clap = { version = "4.2", features = ["cargo", "derive"] }
dyn-clone = "1"
proc-bitfield = "0.2"

log = "0.4"
env_logger = "0.10"

minifb = "0.24"

[profile.release]
#lto = true
