[package]
name = "nesir"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3"
#clap = { version = "3.1", features = ["cargo"] }
argh = "0.1"
dyn-clone = "1"

[profile.release]
lto = true
